// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc9kymJHTsfSBwRoD-9lgKko4Qlqy9q6U',
    appId: '1:233139477632:web:9413a715aa0d943383da65',
    messagingSenderId: '233139477632',
    projectId: 'crmapp-583d8',
    authDomain: 'crmapp-583d8.firebaseapp.com',
    storageBucket: 'crmapp-583d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmnmmNe0XHl__Wd83NH1klk2VMwLLL8n4',
    appId: '1:233139477632:android:ceb107bc22590ae583da65',
    messagingSenderId: '233139477632',
    projectId: 'crmapp-583d8',
    storageBucket: 'crmapp-583d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtc7FGPeSS3pSPpon6WuiVUznzZaFuPdE',
    appId: '1:233139477632:ios:d84d82fa3af6a3f783da65',
    messagingSenderId: '233139477632',
    projectId: 'crmapp-583d8',
    storageBucket: 'crmapp-583d8.firebasestorage.app',
    iosBundleId: 'com.techfifo.crm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtc7FGPeSS3pSPpon6WuiVUznzZaFuPdE',
    appId: '1:233139477632:ios:d84d82fa3af6a3f783da65',
    messagingSenderId: '233139477632',
    projectId: 'crmapp-583d8',
    storageBucket: 'crmapp-583d8.firebasestorage.app',
    iosBundleId: 'com.techfifo.crm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc9kymJHTsfSBwRoD-9lgKko4Qlqy9q6U',
    appId: '1:233139477632:web:17aac0594c19b27483da65',
    messagingSenderId: '233139477632',
    projectId: 'crmapp-583d8',
    authDomain: 'crmapp-583d8.firebaseapp.com',
    storageBucket: 'crmapp-583d8.firebasestorage.app',
  );
}
